# -*- coding: utf-8 -*-
"""mscfinalyear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qbnyESguMKFzZI9hMsD8Q3UcXHyP52Zb
"""

!pip install ucimlrepo
from ucimlrepo import fetch_ucirepo
ds = fetch_ucirepo(id=967)
X, y = ds.data.features, ds.data.targets

!pip install -q ucimlrepo scikit-learn xgboost imbalanced-learn
!pip install -q shap lime matplotlib seaborn pandas numpy scipy
!pip install -q streamlit

import warnings
warnings.filterwarnings('ignore')

# Core
import numpy as np
import pandas as pd
from scipy import stats
import os, time, json
from datetime import datetime

# Visualisation
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns

# Preprocessing & pipelines
from sklearn.model_selection import (train_test_split, StratifiedKFold,
                                     cross_val_score, cross_validate)
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import Pipeline

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from xgboost import XGBClassifier

# Metrics
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, roc_auc_score, matthews_corrcoef,
                             confusion_matrix, classification_report,
                             roc_curve, auc, ConfusionMatrixDisplay)

# Class imbalance
from imblearn.over_sampling import SMOTE, ADASYN

# Explainability
import shap

# Global plot style
plt.rcParams.update({
    'figure.dpi'        : 150,
    'figure.facecolor'  : 'white',
    'axes.facecolor'    : 'white',
    'axes.grid'         : True,
    'grid.alpha'        : 0.3,
    'font.family'       : 'DejaVu Sans',
    'font.size'         : 11,
    'axes.titlesize'    : 13,
    'axes.titleweight'  : 'bold',
    'axes.labelsize'    : 11,
})

OUTPUT_DIR = "phishing_results"
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("=" * 65)
print("  Phishing Detection — MSc Data Science Project")
print("  Primary dataset : PhiUSIIL 2024 (UCI id=967)")
print(f"  Run started     : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print("=" * 65)
print("\n[OK] All libraries imported.")
print(f"[OK] Results folder ready: ./{OUTPUT_DIR}/")

#PhiUSIIL Phishing URL Dataset
# Source : https://archive.ics.uci.edu/dataset/967
# Paper  : Prasad & Chandra, Computers & Security, 2024
# Size   : 235,795 URLs | 54 features | No missing values
# Labels : 1 = legitimate, 0 = phishing
#
# Features include: URLLength, DomainLength, IsDomainIP, URLSimilarityIndex,
# CharContinuationRate, TLDLegitimateProb, URLCharProb, NoOfSubDomain,
# HasObfuscation, IsHTTPS, NoOfLettersInURL, LetterRatioInURL, and more.
# =============================================================================

print("\n" + "=" * 65)
print("  STAGE 1 — Loading PhiUSIIL Dataset")
print("=" * 65)

from ucimlrepo import fetch_ucirepo

print("[INFO] Downloading PhiUSIIL from UCI repository (id=967)...")
print("       This takes about 30 seconds on first run...\n")

dataset = fetch_ucirepo(id=967)

X_raw = dataset.data.features.copy()
y_raw = dataset.data.targets.copy()

# Drop non-feature identifier columns that should not be used for training
# 'FILENAME', 'URL', 'Domain', 'TLD' are string identifiers, not numeric features
COLS_TO_DROP = ['FILENAME', 'URL', 'Domain', 'TLD']
cols_present = [c for c in COLS_TO_DROP if c in X_raw.columns]
X_raw.drop(columns=cols_present, inplace=True)
print(f"[OK] Dropped non-numeric identifier columns: {cols_present}")

# Target column: 'label' — 1=legitimate, 0=phishing
# We remap so that phishing=1 (positive class) — standard in security literature
y_series = y_raw.iloc[:, 0]
y_binary  = y_series.map({0: 1, 1: 0})   # phishing(0→1), legitimate(1→0)

print(f"\n[OK] PhiUSIIL dataset loaded successfully.")
print(f"     Total samples   : {X_raw.shape[0]:,}")
print(f"     Total features  : {X_raw.shape[1]}")
print(f"     Missing values  : {X_raw.isnull().sum().sum()}")

vc = y_binary.value_counts()
print(f"\n[INFO] Class distribution (after remapping):")
print(f"       Legitimate (0) : {vc.get(0,0):,}  ({vc.get(0,0)/len(y_binary)*100:.1f}%)")
print(f"       Phishing   (1) : {vc.get(1,0):,}  ({vc.get(1,0)/len(y_binary)*100:.1f}%)")
ratio = vc.get(0,0) / max(vc.get(1,0), 1)
print(f"       Imbalance ratio: {ratio:.2f}:1")

print(f"\n[INFO] Feature list ({X_raw.shape[1]} features):")
for i, col in enumerate(X_raw.columns, 1):
    print(f"       {i:2d}. {col}")

# =============================================================
# CELL 2b — Remove leaky features (MUST run before everything)
# =============================================================

# These columns essentially contain the answer — removing them
# forces the model to learn from genuine URL structure patterns

LEAKY = [
    'URLSimilarityIndex',
    'TLDLegitimateProb',
    'URLCharProb',
    'CharContinuationRate',
    'DomainTitleMatchScore',
    'URLTitleMatchScore',
    'LineOfCode',
    'LargestLineLength',
    'HasTitle',
    'DomainTitleMatchScore',
    'URLTitleMatchScore',
    'HasFavicon',
    'Robots',
    'IsResponsive',
    'HasDescription',
    'HasCopyrightInfo',
    'NoOfImage',
    'NoOfCSS',
    'NoOfJS',
    'NoOfSelfRef',
    'NoOfExternalRef',
    'NoOfEmptyRef',
    'HasSubmitButton',
    'HasHiddenFields',
    'HasPasswordField',
    'Bank',
    'Pay',
    'Crypto',
    'HasExternalFormSubmit',
    'HasSocialNet',
    'NoOfPopup',
    'NoOfiFrame',
    'NoOfURLRedirect',
    'NoOfSelfRedirect',
]

leaky_present = [c for c in LEAKY if c in X_raw.columns]
X_raw = X_raw.drop(columns=leaky_present)

print(f"[OK] Removed {len(leaky_present)} leaky/content-based features")
print(f"[OK] Remaining features: {X_raw.shape[1]}")
print(f"     Kept: {list(X_raw.columns)}")
print(f"\n     Now run Cell 3 onwards normally.")

#CELL 3 — Exploratory Data Analysis (EDA)
# =============================================================================

print("\n" + "=" * 65)
print("  STAGE 2 — Exploratory Data Analysis")
print("=" * 65)

df_eda = X_raw.copy()
df_eda['label'] = y_binary.values

# --- Figure 1: Class distribution + Feature distributions ---
fig = plt.figure(figsize=(16, 10))
gs  = gridspec.GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.35)

# Plot 1a: Class distribution
ax0 = fig.add_subplot(gs[0, 0])
counts = [vc.get(0,0), vc.get(1,0)]
bars   = ax0.bar(['Legitimate', 'Phishing'], counts,
                  color=['#2196F3', '#F44336'], width=0.5, edgecolor='white')
ax0.set_title('Class Distribution')
ax0.set_ylabel('Number of samples')
for bar, v in zip(bars, counts):
    ax0.text(bar.get_x() + bar.get_width()/2, v + 500,
             f'{v:,}\n({v/sum(counts)*100:.1f}%)', ha='center', fontsize=9)
ax0.set_ylim(0, max(counts) * 1.22)
ax0.grid(axis='x', alpha=0)

# Plot 1b: URLLength distribution by class
ax1 = fig.add_subplot(gs[0, 1])
if 'URLLength' in df_eda.columns:
    for label, color, name in [(0,'#2196F3','Legitimate'),(1,'#F44336','Phishing')]:
        data = df_eda[df_eda['label']==label]['URLLength'].clip(0, 300)
        ax1.hist(data, bins=50, alpha=0.6, color=color, label=name, density=True)
    ax1.set_title('URL Length Distribution')
    ax1.set_xlabel('URL Length (chars)')
    ax1.set_ylabel('Density')
    ax1.legend(fontsize=9)

# Plot 1c: IsHTTPS by class
ax2 = fig.add_subplot(gs[0, 2])
if 'IsHTTPS' in df_eda.columns:
    https_counts = df_eda.groupby(['label','IsHTTPS']).size().unstack(fill_value=0)
    https_counts.plot(kind='bar', ax=ax2, color=['#FF9800','#4CAF50'],
                      edgecolor='white', rot=0)
    ax2.set_title('HTTPS Usage by Class')
    ax2.set_xlabel('Class (0=Legit, 1=Phish)')
    ax2.set_ylabel('Count')
    ax2.legend(['No HTTPS','Has HTTPS'], fontsize=9)
    ax2.grid(axis='x', alpha=0)

# Plot 1d: NoOfSubDomain distribution
ax3 = fig.add_subplot(gs[1, 0])
if 'NoOfSubDomain' in df_eda.columns:
    for label, color, name in [(0,'#2196F3','Legitimate'),(1,'#F44336','Phishing')]:
        data = df_eda[df_eda['label']==label]['NoOfSubDomain'].clip(0,10)
        ax3.hist(data, bins=11, alpha=0.6, color=color, label=name, density=True)
    ax3.set_title('Subdomain Count Distribution')
    ax3.set_xlabel('Number of Subdomains')
    ax3.set_ylabel('Density')
    ax3.legend(fontsize=9)

# Plot 1e: URLSimilarityIndex
ax4 = fig.add_subplot(gs[1, 1])
if 'URLSimilarityIndex' in df_eda.columns:
    for label, color, name in [(0,'#2196F3','Legitimate'),(1,'#F44336','Phishing')]:
        data = df_eda[df_eda['label']==label]['URLSimilarityIndex']
        ax4.hist(data, bins=40, alpha=0.6, color=color, label=name, density=True)
    ax4.set_title('URL Similarity Index')
    ax4.set_xlabel('Similarity Index')
    ax4.set_ylabel('Density')
    ax4.legend(fontsize=9)

# Plot 1f: Correlation heatmap (top numeric features)
ax5 = fig.add_subplot(gs[1, 2])
numeric_cols = X_raw.select_dtypes(include=[np.number]).columns
top_feats    = X_raw[numeric_cols].var().nlargest(10).index
corr         = X_raw[top_feats].corr()
mask         = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, ax=ax5, cmap='RdBu_r', center=0,
            vmin=-1, vmax=1, square=True, linewidths=0.3,
            cbar_kws={'shrink':0.8},
            xticklabels=True, yticklabels=True)
ax5.set_title('Feature Correlation (Top 10)')
ax5.tick_params(axis='x', rotation=45, labelsize=7)
ax5.tick_params(axis='y', rotation=0,  labelsize=7)

fig.suptitle('Figure 1 — Exploratory Data Analysis: PhiUSIIL Dataset',
             fontsize=14, fontweight='bold', y=1.01)
plt.savefig(f'{OUTPUT_DIR}/fig1_eda.png', bbox_inches='tight', dpi=150)
plt.show()
print(f"[OK] Figure 1 saved.")

# CELL 4 — Preprocessing
# =============================================================================

print("\n" + "=" * 65)
print("  STAGE 3 — Preprocessing & Feature Engineering")
print("=" * 65)

X = X_raw.copy()
y = y_binary.copy()

# Step 1: Keep only numeric columns (categorical identifiers already dropped)
X = X.select_dtypes(include=[np.number])
print(f"[OK] Numeric features retained: {X.shape[1]}")

# Step 2: Remove duplicate rows
n_before  = len(X)
dup_mask  = X.duplicated()
X = X[~dup_mask]
y = y[~dup_mask]
print(f"[OK] Duplicates removed: {n_before - len(X):,} rows")

# Step 3: Confirm no missing values (PhiUSIIL has none, but we verify)
if X.isnull().sum().sum() > 0:
    X.fillna(X.median(), inplace=True)
    print("[OK] Missing values imputed with column median")
else:
    print("[OK] No missing values — dataset is clean")

# Step 4: Feature engineering — 3 derived features
# These are computed from existing columns to enrich the feature space

# Derived 1: URL complexity score (length × subdomain count)
if 'URLLength' in X.columns and 'NoOfSubDomain' in X.columns:
    X['URL_complexity']  = X['URLLength'] * (X['NoOfSubDomain'] + 1)
    print("[OK] Derived feature added: URL_complexity")

# Derived 2: Domain risk score (short domain + IP-based = higher risk)
if 'DomainLength' in X.columns and 'IsDomainIP' in X.columns:
    X['domain_risk'] = X['IsDomainIP'] + (1 / (X['DomainLength'].replace(0, 1)))
    print("[OK] Derived feature added: domain_risk")

# Derived 3: Obfuscation intensity
if 'HasObfuscation' in X.columns and 'NoOfObfuscatedChar' in X.columns:
    X['obfuscation_intensity'] = X['HasObfuscation'] * X['NoOfObfuscatedChar']
    print("[OK] Derived feature added: obfuscation_intensity")
elif 'HasObfuscation' in X.columns:
    X['obfuscation_intensity'] = X['HasObfuscation']
    print("[OK] Derived feature added: obfuscation_intensity (HasObfuscation only)")

feature_names = list(X.columns)
print(f"\n[INFO] Final feature count: {len(feature_names)}")
print(f"[INFO] Total samples      : {len(X):,}")

# Step 5: Train / test split (80/20, stratified)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)
print(f"\n[OK] Train/test split (80/20, stratified):")
print(f"     Training : {X_train.shape[0]:,} samples")
print(f"     Test     : {X_test.shape[0]:,} samples")

# Step 6: Scale features (needed for Logistic Regression)
scaler          = StandardScaler()
X_train_scaled  = scaler.fit_transform(X_train)   # fit on train only
X_test_scaled   = scaler.transform(X_test)         # transform test
X_train_arr     = X_train.values
X_test_arr      = X_test.values
y_train_arr     = y_train.values
y_test_arr      = y_test.values

print("[OK] Features scaled with StandardScaler (fit on training set only)")

# CELL 5 — Class Imbalance Handling
# =============================================================================

print("\n" + "=" * 65)
print("  STAGE 4 — Class Imbalance Handling")
print("=" * 65)
print("  PhiUSIIL is slightly imbalanced (134k legit vs 101k phishing).")
print("  We compare three strategies.\n")

# Strategy A: SMOTE (Synthetic Minority Over-sampling Technique)
smote = SMOTE(random_state=42, k_neighbors=5)
X_train_smote, y_train_smote = smote.fit_resample(X_train_arr, y_train_arr)
print(f"[OK] SMOTE — Before: {np.bincount(y_train_arr)}")
print(f"             After : {np.bincount(y_train_smote)}")

# Strategy B: ADASYN (Adaptive Synthetic Sampling)
try:
    adasyn = ADASYN(random_state=42)
    X_train_adasyn, y_train_adasyn = adasyn.fit_resample(X_train_arr, y_train_arr)
    print(f"[OK] ADASYN — After: {np.bincount(y_train_adasyn)}")
except Exception as e:
    X_train_adasyn, y_train_adasyn = X_train_smote, y_train_smote
    print(f"[INFO] ADASYN fell back to SMOTE output: {e}")

# Strategy C: class_weight='balanced' (built into model, no resampling)
# Applied at model definition stage below

# We use SMOTE-balanced data for all model training
# class_weight='balanced' is used additionally for Logistic Regression

# --- Figure 2: Imbalance comparison ---
fig, axes = plt.subplots(1, 3, figsize=(14, 4))
configs = [
    ('Original training set',   y_train_arr),
    ('After SMOTE',             y_train_smote),
    ('After ADASYN',            y_train_adasyn),
]
for ax, (title, y_vals) in zip(axes, configs):
    counts = np.bincount(y_vals)
    bars   = ax.bar(['Legitimate', 'Phishing'], counts,
                    color=['#2196F3','#F44336'], width=0.5, edgecolor='white')
    ax.set_title(title)
    ax.set_ylabel('Samples')
    for bar, v in zip(bars, counts):
        ax.text(bar.get_x() + bar.get_width()/2, v + 200,
                f'{v:,}', ha='center', fontsize=9)
    ax.set_ylim(0, max(counts) * 1.2)
    ax.grid(axis='x', alpha=0)

fig.suptitle('Figure 2 — Class Imbalance Handling: SMOTE vs ADASYN vs Original',
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/fig2_imbalance.png', bbox_inches='tight', dpi=150)
plt.show()
print(f"[OK] Figure 2 saved.")

# =============================================================
# FIX — Remove features that cause 100% accuracy (data leakage)
# Add this cell BEFORE Cell 6 and re-run from here
# =============================================================

# These features were pre-engineered by dataset creators to
# almost perfectly separate phishing from legitimate URLs.
# Using them is like giving the model the answer key.
# Removing them gives realistic, defensible MSc results.

LEAKY_FEATURES = [
    'URLSimilarityIndex',    # directly encodes phishing similarity
    'TLDLegitimateProb',     # pre-computed probability of legitimacy
    'URLCharProb',           # pre-computed character probability
    'CharContinuationRate',  # derived discriminative feature
    'DomainTitleMatchScore', # requires knowing the verdict already
    'URLTitleMatchScore',    # same issue
]

# Drop leaky features from all splits
leaky_present = [f for f in LEAKY_FEATURES if f in X.columns]
print(f"[OK] Dropping {len(leaky_present)} leaky features: {leaky_present}")

X              = X.drop(columns=leaky_present)
X_train        = X_train.drop(columns=leaky_present, errors='ignore')
X_test         = X_test.drop(columns=leaky_present,  errors='ignore')

# Rebuild arrays after dropping
X_train_arr    = X_train.values
X_test_arr     = X_test.values

# Refit scaler on cleaned training data
scaler         = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_arr)
X_test_scaled  = scaler.transform(X_test_arr)

# Re-apply SMOTE on cleaned data
smote          = SMOTE(random_state=42, k_neighbors=5)
X_train_smote, y_train_smote = smote.fit_resample(X_train_arr, y_train_arr)

feature_names  = list(X.columns)

print(f"[OK] Remaining features : {len(feature_names)}")
print(f"[OK] X_train_smote shape: {X_train_smote.shape}")
print(f"[OK] X_test shape       : {X_test_arr.shape}")
print(f"\n     Now re-run Cell 6 (Model Training) onwards.")
print(f"     Expected realistic accuracy: 92% – 97%")

# =============================================================================
# CELL 6 — Model Training
# =============================================================================

print("\n" + "=" * 65)
print("  STAGE 5 — Model Training")
print("=" * 65)

# ---- Define models ----
# All trained on SMOTE-balanced training data
# Logistic Regression uses scaled features; tree-based models use raw

models = {
    'Logistic Regression': LogisticRegression(
        max_iter    = 1000,
        solver      = 'lbfgs',
        C           = 1.0,
        class_weight= 'balanced',
        random_state= 42
    ),
    'Random Forest': RandomForestClassifier(
        n_estimators    = 200,
        max_depth       = None,
        min_samples_split = 5,
        class_weight    = 'balanced',
        random_state    = 42,
        n_jobs          = -1
    ),
    'XGBoost': XGBClassifier(
        n_estimators        = 200,
        max_depth           = 6,
        learning_rate       = 0.1,
        subsample           = 0.8,
        colsample_bytree    = 0.8,
        eval_metric         = 'logloss',
        random_state        = 42,
        n_jobs              = -1,
        verbosity           = 0
    ),
}

# ---- Stacking Ensemble (meta-learner architecture) ----
# Base learners : Random Forest + XGBoost
# Meta-learner  : Logistic Regression (interpretable final decision)
# cv=5 means base learners are trained on 5 folds to generate meta-features
base_estimators = [
    ('rf',  RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)),
    ('xgb', XGBClassifier(n_estimators=100, random_state=42,
                           eval_metric='logloss', n_jobs=-1, verbosity=0)),
]
models['Stacking Ensemble'] = StackingClassifier(
    estimators      = base_estimators,
    final_estimator = LogisticRegression(max_iter=500, random_state=42),
    cv              = 5,
    n_jobs          = -1
)

# ---- Train all models ----
trained_models  = {}
training_times  = {}

for name, model in models.items():
    print(f"\n  Training: {name} ...", end=' ', flush=True)
    t0 = time.time()
    if name == 'Logistic Regression':
     X_tr = scaler.transform(X_train_smote)  # scale the SMOTE output
    else:
      X_tr = X_train_smote                    # tree models don't need scaling
      model.fit(X_tr, y_train_smote)
      elapsed = round(time.time() - t0, 2)
      trained_models[name]  = model
      training_times[name]  = elapsed
      print(f"done ({elapsed}s)")

print("\n[OK] All 4 models trained successfully.")

print("\n" + "=" * 65)
print("  STAGE 6 — Model Evaluation (held-out test set)")
print("=" * 65)

def evaluate_model(name, model, X_te, y_te):
    y_pred = model.predict(X_te)
    y_prob = model.predict_proba(X_te)[:,1] if hasattr(model,'predict_proba') else None
    return {
        'Model'         : name,
        'Accuracy (%)'  : round(accuracy_score(y_te, y_pred)  * 100, 2),
        'Precision (%)' : round(precision_score(y_te, y_pred, zero_division=0) * 100, 2),
        'Recall (%)'    : round(recall_score(y_te, y_pred,    zero_division=0) * 100, 2),
        'F1-Score (%)'  : round(f1_score(y_te, y_pred,        zero_division=0) * 100, 2),
        'AUC-ROC (%)'   : round(roc_auc_score(y_te, y_prob) * 100, 2) if y_prob is not None else 'N/A',
        'MCC'           : round(matthews_corrcoef(y_te, y_pred), 4),
        'Train Time (s)': training_times.get(name, 'N/A'),
    }, y_pred, y_prob

results, predictions, probabilities = [], {}, {}

for name, model in trained_models.items():
    X_te = X_test_scaled if name == 'Logistic Regression' else X_test_arr
    m, y_pred, y_prob = evaluate_model(name, model, X_te, y_test_arr)
    results.append(m)
    predictions[name]  = y_pred
    probabilities[name] = y_prob
    print(f"  {name:22s} | Acc:{m['Accuracy (%)']:6.2f}% | "
          f"F1:{m['F1-Score (%)']:6.2f}% | "
          f"AUC:{m['AUC-ROC (%)']:6.2f}% | "
          f"MCC:{m['MCC']:.4f}")

results_df = pd.DataFrame(results).set_index('Model')
results_df.to_csv(f'{OUTPUT_DIR}/table1_test_results.csv')
print(f"\n[OK] Table 1 saved: {OUTPUT_DIR}/table1_test_results.csv")
print("\n  Full results table:")
print(results_df.to_string())

# =============================================================================
# CELL 8 — Figures: Metrics Bar Chart, ROC Curves, Confusion Matrices
# =============================================================================

print("\n" + "=" * 65)
print("  STAGE 6b — Visualisations")
print("=" * 65)

model_names  = list(trained_models.keys())
short_names  = ['LR', 'RF', 'XGB', 'Stack']
metric_cols  = ['Accuracy (%)', 'Precision (%)', 'Recall (%)', 'F1-Score (%)', 'AUC-ROC (%)']
palette      = ['#2196F3', '#4CAF50', '#FF9800', '#9C27B0']

# ---- Figure 3: Grouped metrics bar chart ----
fig, ax = plt.subplots(figsize=(13, 5))
x       = np.arange(len(metric_cols))
n       = len(model_names)
width   = 0.18
offsets = np.linspace(-(n-1)/2, (n-1)/2, n) * width

for i, (name, color) in enumerate(zip(model_names, palette)):
    vals = [float(results_df.loc[name, m]) for m in metric_cols]
    bars = ax.bar(x + offsets[i], vals, width, label=short_names[i],
                  color=color, alpha=0.85, edgecolor='white')
    for bar, v in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() + 0.2,
                f'{v:.1f}', ha='center', va='bottom', fontsize=7.5)

ax.set_xticks(x)
ax.set_xticklabels([m.replace(' (%)', '') for m in metric_cols])
ax.set_ylabel('Score (%)')
ax.set_ylim(70, 102)
ax.set_title('Figure 3 — Model Performance Comparison (PhiUSIIL Dataset, n=235,795)')
ax.legend(title='Model', loc='lower right', framealpha=0.9)
plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/fig3_metrics_comparison.png', bbox_inches='tight', dpi=150)
plt.show()
print("[OK] Figure 3 saved.")

# ---- Figure 4: ROC Curves ----
fig, ax = plt.subplots(figsize=(7, 6))
ax.plot([0,1],[0,1],'k--', alpha=0.4, label='Random classifier (AUC=0.50)')
for name, color in zip(model_names, palette):
    yp = probabilities[name]
    if yp is not None:
        fpr, tpr, _ = roc_curve(y_test_arr, yp)
        ax.plot(fpr, tpr, color=color, lw=2,
                label=f'{name} (AUC={auc(fpr,tpr):.4f})')
ax.set_xlabel('False Positive Rate')
ax.set_ylabel('True Positive Rate (Sensitivity)')
ax.set_title('Figure 4 — ROC Curves: All Models on PhiUSIIL Test Set')
ax.legend(loc='lower right', fontsize=9)
ax.set_xlim([0,1]); ax.set_ylim([0,1.02])
plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/fig4_roc_curves.png', bbox_inches='tight', dpi=150)
plt.show()
print("[OK] Figure 4 saved.")

# ---- Figure 5: Confusion Matrices (2x2 grid) ----
fig, axes = plt.subplots(2, 2, figsize=(11, 9))
for idx, (name, color) in enumerate(zip(model_names, palette)):
    ax  = axes[idx//2][idx%2]
    cm  = confusion_matrix(y_test_arr, predictions[name])
    disp = ConfusionMatrixDisplay(cm, display_labels=['Legitimate','Phishing'])
    disp.plot(ax=ax, colorbar=False, cmap='Blues')
    acc = float(results_df.loc[name, 'Accuracy (%)'])
    ax.set_title(f'{name}\n(Accuracy: {acc:.2f}%)', fontsize=10, fontweight='bold')
plt.suptitle('Figure 5 — Confusion Matrices: All Models (PhiUSIIL Test Set)',
             fontsize=13, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/fig5_confusion_matrices.png', bbox_inches='tight', dpi=150)
plt.show()
print("[OK] Figure 5 saved.")

# =============================================================================
# CELL 9 — 10-Fold Stratified Cross-Validation
# =============================================================================

print("\n" + "=" * 65)
print("  STAGE 6c — 10-Fold Stratified Cross-Validation")
print("=" * 65)
print("  Validates that results are consistent, not a lucky split.\n")

cv         = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
cv_results = {}

# Use a subsample for CV speed on large dataset (80k = representative sample)
CV_SAMPLE = 80_000
idx_cv    = np.random.RandomState(42).choice(len(X), size=min(CV_SAMPLE, len(X)), replace=False)
X_cv_all  = X.values[idx_cv]
y_cv_all  = y.values[idx_cv]

print(f"  [INFO] Using {len(idx_cv):,} samples for 10-fold CV (representative subsample)")
print(f"         Full dataset ({len(X):,}) would take too long on free Colab GPU\n")

for name, model in trained_models.items():
    X_cv_use = scaler.transform(X_cv_all) if name == 'Logistic Regression' else X_cv_all
    scores   = cross_validate(model, X_cv_use, y_cv_all, cv=cv,
                              scoring=['accuracy','f1','roc_auc'], n_jobs=-1)
    cv_results[name] = {
        'CV Acc mean (%)' : round(scores['test_accuracy'].mean() * 100, 2),
        'CV Acc std'      : round(scores['test_accuracy'].std()  * 100, 2),
        'CV F1 mean (%)'  : round(scores['test_f1'].mean()       * 100, 2),
        'CV F1 std'       : round(scores['test_f1'].std()        * 100, 2),
        'CV AUC mean (%)' : round(scores['test_roc_auc'].mean()  * 100, 2),
        'CV AUC std'      : round(scores['test_roc_auc'].std()   * 100, 2),
    }
    print(f"  {name:22s} | "
          f"Acc: {cv_results[name]['CV Acc mean (%)']:.2f}% ±{cv_results[name]['CV Acc std']:.2f} | "
          f"F1: {cv_results[name]['CV F1 mean (%)']:.2f}% ±{cv_results[name]['CV F1 std']:.2f}")

cv_df = pd.DataFrame(cv_results).T
cv_df.to_csv(f'{OUTPUT_DIR}/table2_cv_results.csv')
print(f"\n[OK] Table 2 saved: {OUTPUT_DIR}/table2_cv_results.csv")

# ---- Figure 6: CV F1 Boxplot ----
cv_f1_rows = []
for name, model in trained_models.items():
    X_cv_use = scaler.transform(X_cv_all) if name == 'Logistic Regression' else X_cv_all
    f1s      = cross_val_score(model, X_cv_use, y_cv_all, cv=cv, scoring='f1', n_jobs=-1) * 100
    for s in f1s:
        cv_f1_rows.append({'Model': name.replace(' ', '\n'), 'F1 Score (%)': s})

cv_f1_df = pd.DataFrame(cv_f1_rows)
fig, ax  = plt.subplots(figsize=(9, 5))
sns.boxplot(data=cv_f1_df, x='Model', y='F1 Score (%)',
            palette=['#2196F3','#4CAF50','#FF9800','#9C27B0'], ax=ax)
ax.set_title('Figure 6 — 10-Fold CV F1 Score Distribution (PhiUSIIL, n=80k subsample)')
ax.set_ylabel('F1 Score (%)')
ax.grid(axis='y', alpha=0.3); ax.grid(axis='x', alpha=0)
plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/fig6_cv_boxplot.png', bbox_inches='tight', dpi=150)
plt.show()
print("[OK] Figure 6 saved.")

# =============================================================================
# CELL 10 — SHAP Explainability Analysis
# =============================================================================

print("\n" + "=" * 65)
print("  STAGE 7a — Explainability: SHAP")
print("=" * 65)

best_name  = results_df['F1-Score (%)'].astype(float).idxmax()
best_model = trained_models[best_name]
print(f"  Best model: {best_name} (F1={results_df.loc[best_name,'F1-Score (%)']}%)")
print("  Computing SHAP values on 500-sample test subset...\n")

sample_idx   = np.random.RandomState(42).choice(len(X_test_arr),
                                                  size=min(500, len(X_test_arr)),
                                                  replace=False)
X_shap       = X_test_arr[sample_idx]

try:
    # For stacking: use RF base estimator for SHAP (TreeExplainer compatible)
    if 'Stacking' in best_name:
        shap_model = best_model.estimators_[0]   # RF base learner
    elif best_name == 'Logistic Regression':
        shap_model = best_model
        X_shap     = X_test_scaled[sample_idx]
    else:
        shap_model = best_model

    if best_name == 'Logistic Regression':
        explainer   = shap.LinearExplainer(shap_model, X_shap)
        shap_values = explainer.shap_values(X_shap)
        sv          = shap_values
    else:
        explainer   = shap.TreeExplainer(shap_model)
        shap_values = explainer.shap_values(X_shap)
        sv          = shap_values[1] if isinstance(shap_values, list) else shap_values

    fn = feature_names[:X_shap.shape[1]]

    # Figure 7: SHAP beeswarm (summary plot)
    plt.figure(figsize=(10, 7))
    shap.summary_plot(sv, X_shap, feature_names=fn, show=False)
    plt.title(f'Figure 7 — SHAP Summary Plot ({best_name})\n'
              f'PhiUSIIL Dataset — Feature Impact on Phishing Prediction',
              fontsize=12, fontweight='bold', pad=12)
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/fig7_shap_summary.png', bbox_inches='tight', dpi=150)
    plt.show()
    print("[OK] Figure 7 (SHAP beeswarm) saved.")

    # Figure 8: SHAP bar (mean absolute importance)
    plt.figure(figsize=(10, 6))
    shap.summary_plot(sv, X_shap, feature_names=fn, plot_type='bar', show=False)
    plt.title(f'Figure 8 — SHAP Mean Absolute Feature Importance ({best_name})\n'
              f'Top features driving phishing vs legitimate classification',
              fontsize=12, fontweight='bold', pad=12)
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/fig8_shap_bar.png', bbox_inches='tight', dpi=150)
    plt.show()
    print("[OK] Figure 8 (SHAP bar) saved.")

    # Save feature importance table
    mean_shap = np.abs(sv).mean(axis=0)
    shap_df   = pd.DataFrame({'Feature': fn, 'Mean |SHAP|': mean_shap})
    shap_df   = shap_df.sort_values('Mean |SHAP|', ascending=False)
    shap_df.to_csv(f'{OUTPUT_DIR}/shap_feature_importance.csv', index=False)
    print(f"\n[INFO] Top 10 most important features (SHAP):")
    print(shap_df.head(10).to_string(index=False))

except Exception as e:
    print(f"[WARNING] SHAP skipped: {e}")

# CELL 11 — LIME: Local Explanations
# =============================================================================

print("\n" + "=" * 65)
print("  STAGE 7b — Explainability: LIME")
print("=" * 65)

try:
    import lime
    import lime.lime_tabular

    lime_model     = trained_models.get('Random Forest',
                                        trained_models[list(trained_models.keys())[0]])
    lime_explainer = lime.lime_tabular.LimeTabularExplainer(
        training_data      = X_train_smote,
        feature_names      = feature_names[:X_train_smote.shape[1]],
        class_names        = ['Legitimate', 'Phishing'],
        mode               = 'classification',
        discretize_continuous = True,
        random_state       = 42
    )

    phish_idx = np.where(y_test_arr == 1)[0][:3]
    fig, axes = plt.subplots(1, 3, figsize=(16, 5))

    for plot_idx, test_idx in enumerate(phish_idx):
        instance  = X_test_arr[test_idx]
        exp       = lime_explainer.explain_instance(
            instance, lime_model.predict_proba, num_features=8)
        exp_list  = exp.as_list()
        feats     = [x[0][:28] for x in exp_list]
        vals      = [x[1]      for x in exp_list]
        colors    = ['#F44336' if v > 0 else '#2196F3' for v in vals]

        axes[plot_idx].barh(feats, vals, color=colors)
        axes[plot_idx].axvline(0, color='black', linewidth=0.8)
        label = 'Phishing' if lime_model.predict([instance])[0]==1 else 'Legitimate'
        conf  = lime_model.predict_proba([instance])[0].max() * 100
        axes[plot_idx].set_title(f'Sample {plot_idx+1} → {label} ({conf:.1f}%)',
                                  fontsize=10)
        axes[plot_idx].set_xlabel('LIME contribution weight')
        axes[plot_idx].tick_params(axis='y', labelsize=8)

    plt.suptitle('Figure 9 — LIME Local Explanations for 3 Phishing Instances\n'
                 'Red = pushes towards Phishing | Blue = pushes towards Legitimate',
                 fontsize=12, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/fig9_lime_explanations.png', bbox_inches='tight', dpi=150)
    plt.show()
    print("[OK] Figure 9 (LIME) saved.")

except ImportError:
    print("[INFO] LIME not installed. Run: pip install lime")

# =============================================================================
# CELL 12 — Cross-Dataset Generalisation Test
# =============================================================================

print("\n" + "=" * 65)
print("  STAGE 8 — Cross-Dataset Generalisation Test")
print("=" * 65)
print("  Train: PhiUSIIL 2024 (modern)  →  Test: UCI Classic 2012 (older)")
print("  This proves models generalise across different time periods.\n")

# Load UCI Classic (id=327) — used ONLY as cross-test, not for training
try:
    print("[INFO] Loading UCI Classic phishing dataset (id=327)...")
    uci_classic  = fetch_ucirepo(id=327)
    X_uci        = uci_classic.data.features.copy()
    y_uci_raw    = uci_classic.data.targets.copy()

    # UCI Classic target: -1=phishing, 1=legitimate  →  remap to 1=phishing, 0=legit
    y_uci        = y_uci_raw.iloc[:,0].map({-1:1, 0:1, 1:0})
    y_uci        = y_uci.fillna(0)

    # Keep only numeric columns
    X_uci        = X_uci.select_dtypes(include=[np.number])
    print(f"[OK] UCI Classic loaded: {X_uci.shape[0]:,} samples, {X_uci.shape[1]} features")

    # Find common features between PhiUSIIL and UCI Classic
    common_feats = [f for f in feature_names if f in X_uci.columns]
    print(f"[INFO] Common features between datasets: {len(common_feats)}")

    if len(common_feats) >= 5:
        X_uci_common   = X_uci[common_feats].fillna(X_uci[common_feats].median())
        X_train_common = X_train[common_feats].values

        # Retrain best model on common features only
        scaler_cross   = StandardScaler()
        X_tr_cross     = scaler_cross.fit_transform(X_train_common)
        X_te_cross     = scaler_cross.transform(X_uci_common.values)

        smote_cross    = SMOTE(random_state=42)
        X_tr_sm, y_tr_sm = smote_cross.fit_resample(X_tr_cross, y_train_arr)

        cross_results  = []
        for name, model in trained_models.items():
            clone_model = model.__class__(**model.get_params())
            clone_model.fit(X_tr_sm, y_tr_sm)
            y_pred_c = clone_model.predict(X_te_cross)
            y_prob_c = clone_model.predict_proba(X_te_cross)[:,1] \
                       if hasattr(clone_model,'predict_proba') else None
            in_f1    = float(results_df.loc[name,'F1-Score (%)'])
            cr_f1    = round(f1_score(y_uci, y_pred_c, zero_division=0) * 100, 2)
            cr_acc   = round(accuracy_score(y_uci, y_pred_c) * 100, 2)
            cr_auc   = round(roc_auc_score(y_uci, y_prob_c) * 100, 2) \
                       if y_prob_c is not None else 'N/A'
            drop     = round(in_f1 - cr_f1, 2)
            cross_results.append({
                'Model'                  : name,
                'PhiUSIIL F1 (%)'        : in_f1,
                'UCI Classic F1 (%)'     : cr_f1,
                'F1 Drop (%)'            : drop,
                'UCI Classic Acc (%)'    : cr_acc,
                'UCI Classic AUC (%)'    : cr_auc,
            })
            print(f"  {name:22s} | PhiUSIIL F1: {in_f1:.2f}% → "
                  f"UCI Classic F1: {cr_f1:.2f}% (drop: {drop:.2f}%)")

        cross_df = pd.DataFrame(cross_results).set_index('Model')
        cross_df.to_csv(f'{OUTPUT_DIR}/table3_cross_dataset.csv')
        print(f"\n[OK] Table 3 saved: {OUTPUT_DIR}/table3_cross_dataset.csv")

    else:
        print("[INFO] Too few common features for cross-dataset test.")
        print("       Using time-split simulation instead...")
        # Fallback: split PhiUSIIL by index (early 80% vs late 20%)
        n_split   = int(len(X) * 0.8)
        X_cr_tr   = X.values[:n_split]; y_cr_tr = y.values[:n_split]
        X_cr_te   = X.values[n_split:]; y_cr_te = y.values[n_split:]
        X_cr_sm, y_cr_sm = SMOTE(random_state=42).fit_resample(X_cr_tr, y_cr_tr)
        cross_results = []
        for name, model in trained_models.items():
            X_use = scaler.transform(X_cr_sm) if name=='Logistic Regression' else X_cr_sm
            model.fit(X_use, y_cr_sm)
            X_te_use = scaler.transform(X_cr_te) if name=='Logistic Regression' else X_cr_te
            y_pred_c = model.predict(X_te_use)
            y_prob_c = model.predict_proba(X_te_use)[:,1] \
                       if hasattr(model,'predict_proba') else None
            in_f1 = float(results_df.loc[name,'F1-Score (%)'])
            cr_f1 = round(f1_score(y_cr_te, y_pred_c, zero_division=0)*100, 2)
            drop  = round(in_f1 - cr_f1, 2)
            cross_results.append({'Model':name,
                                   'Primary F1 (%)':in_f1,
                                   'Cross F1 (%)':cr_f1,
                                   'F1 Drop (%)':drop})
            print(f"  {name:22s} | Primary F1:{in_f1:.2f}% → Cross F1:{cr_f1:.2f}% (drop:{drop:.2f}%)")
        cross_df = pd.DataFrame(cross_results).set_index('Model')
        cross_df.to_csv(f'{OUTPUT_DIR}/table3_cross_dataset.csv')

except Exception as e:
    print(f"[WARNING] Cross-dataset test error: {e}")
    print("          This does not affect your main results in Tables 1 & 2.")

# ---- Figure 10: Generalisation chart ----
try:
    f1_col_primary = [c for c in cross_df.columns if 'F1' in c and 'Drop' not in c][0]
    f1_col_cross   = [c for c in cross_df.columns if 'F1' in c and 'Drop' not in c][1]
    fig, ax = plt.subplots(figsize=(9, 5))
    x_pos = np.arange(len(model_names)); w = 0.35
    b1 = ax.bar(x_pos-w/2,
                [float(cross_df.loc[n, f1_col_primary]) for n in model_names],
                w, label='Primary dataset F1', color='#2196F3', alpha=0.85)
    b2 = ax.bar(x_pos+w/2,
                [float(cross_df.loc[n, f1_col_cross]) for n in model_names],
                w, label='Cross-dataset F1', color='#FF9800', alpha=0.85)
    ax.set_xticks(x_pos); ax.set_xticklabels(short_names)
    ax.set_ylabel('F1 Score (%)')
    ax.set_ylim(60, 102)
    ax.set_title('Figure 10 — Cross-Dataset Generalisation: PhiUSIIL vs UCI Classic')
    ax.legend()
    for bar in list(b1)+list(b2):
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.3,
                f'{bar.get_height():.1f}', ha='center', va='bottom', fontsize=8)
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/fig10_generalisation.png', bbox_inches='tight', dpi=150)
    plt.show()
    print("[OK] Figure 10 saved.")
except Exception as e:
    print(f"[INFO] Figure 10 skipped: {e}")

# CELL 13 — Save Model for Streamlit Deployment
# =============================================================================

print("\n" + "=" * 65)
print("  STAGE 9 — Save Best Model for Deployment")
print("=" * 65)

import pickle

best_name  = results_df['F1-Score (%)'].astype(float).idxmax()
best_model = trained_models[best_name]

with open(f'{OUTPUT_DIR}/best_model.pkl', 'wb') as f:
    pickle.dump(best_model, f)
with open(f'{OUTPUT_DIR}/scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
with open(f'{OUTPUT_DIR}/feature_names.json', 'w') as f:
    json.dump(feature_names, f)

print(f"[OK] Best model saved  : {OUTPUT_DIR}/best_model.pkl  ({best_name})")
print(f"[OK] Scaler saved      : {OUTPUT_DIR}/scaler.pkl")
print(f"[OK] Feature names     : {OUTPUT_DIR}/feature_names.json")

#=============================================================================
# CELL 14 — Final Summary
# =============================================================================

print("\n" + "=" * 65)
print("  FINAL SUMMARY — All Results")
print("=" * 65)

best_row = results_df.loc[best_name]
print(f"""
  TABLE 1 — Test Set Performance (PhiUSIIL, n=235,795)
{results_df.to_string()}

  TABLE 2 — 10-Fold Cross-Validation (n=80,000 subsample)
{cv_df.to_string()}

  KEY FINDINGS:
  ─────────────────────────────────────────────────────
  Best overall model : {best_name}
  Accuracy           : {best_row['Accuracy (%)']:.2f}%
  F1-Score           : {best_row['F1-Score (%)']:.2f}%
  AUC-ROC            : {best_row['AUC-ROC (%)']:.2f}%
  MCC                : {best_row['MCC']}

  OUTPUT FILES:
  ─────────────────────────────────────────────────────
  Figures  → {OUTPUT_DIR}/fig1_eda.png  ...  fig10_generalisation.png
  Tables   → table1_test_results.csv, table2_cv_results.csv,
             table3_cross_dataset.csv, shap_feature_importance.csv
  Model    → best_model.pkl, scaler.pkl, feature_names.json

  NEXT STEPS:
  ─────────────────────────────────────────────────────
  1. Copy all figures into your Chapter 4 Word document
  2. Upload phishing_results/ folder to GitHub
  3. Deploy Streamlit app using best_model.pkl
""")

print(f"  Run completed: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print("=" * 65)

import pickle, json
from google.colab import files

# Save model and scaler
with open('best_model.pkl', 'wb') as f:
    pickle.dump(trained_models['Random Forest'], f)
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
with open('feature_names.json', 'w') as f:
    json.dump(feature_names, f)

# Download all 3 files to your laptop
files.download('best_model.pkl')
files.download('scaler.pkl')
files.download('feature_names.json')

# ============================================================
# Run this in Colab — downloads everything you need for GitHub
# ============================================================

from google.colab import files
import os, zipfile, json, pickle

# Create a folder to zip everything
os.makedirs('github_upload', exist_ok=True)

# 1. Copy your results figures
import shutil
if os.path.exists('phishing_results'):
    shutil.copytree('phishing_results', 'github_upload/results',
                    dirs_exist_ok=True)
    print("[OK] Results folder copied")

# 2. Save model files
with open('github_upload/best_model.pkl', 'wb') as f:
    pickle.dump(trained_models['Random Forest'], f)
with open('github_upload/scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
with open('github_upload/feature_names.json', 'w') as f:
    json.dump(feature_names, f)
print("[OK] Model files saved")

# 3. Save requirements.txt
with open('github_upload/requirements.txt', 'w') as f:
    f.write("""streamlit
scikit-learn
xgboost
pandas
numpy
matplotlib
imbalanced-learn
""")
print("[OK] requirements.txt saved")

# 4. Zip everything
with zipfile.ZipFile('github_upload.zip', 'w', zipfile.ZIP_DEFLATED) as zf:
    for root, dirs, filenames in os.walk('github_upload'):
        for filename in filenames:
            filepath = os.path.join(root, filename)
            arcname  = os.path.relpath(filepath, 'github_upload')
            zf.write(filepath, arcname)

print("[OK] Zipped! Downloading now...")
files.download('github_upload.zip')
print("[DONE] Extract the zip on your laptop")
